matrix:
  include:
    - os: linux
      env: ACTION=docker
      language: generic
      dist: trusty
      sudo: required
      services:
        - docker
    - os: osx
      env: ACTION=SwiftPM
      language: objective-c
      osx_image: xcode10.2

script:
  - make test-$ACTION
